#!/bin/bash
export PATH=/usr/bin:$PATH
#gfortran -c -fdefault-real-8 test.f
#gfortran -o a1.out test.o
#./a1.out

gfortran -c test.stokes.f
gfortran -o a.out test.stokes.o
./a.out

gfortran -c test.stokes_PW.f
gfortran -o a_PW.out test.stokes_PW.o
./a_PW.out
